# Generated by Django 4.2.1 on 2023-06-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_favorite_books_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_users',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
