# Generated by Django 4.2.1 on 2023-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_followed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followed_users',
            field=models.ManyToManyField(blank=True, to='profiles.userprofile'),
        ),
    ]
