# Generated by Django 4.2.1 on 2023-06-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_followed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers_users',
            field=models.ManyToManyField(blank=True, related_name='followers', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='following', to='profiles.userprofile'),
        ),
    ]
