# Generated by Django 4.2.1 on 2023-06-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_followers_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_users',
        ),
    ]
