# Generated by Django 4.2.1 on 2023-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_followers_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_users',
            field=models.ManyToManyField(blank=True, related_name='followers', to='profiles.userprofile'),
        ),
    ]
